### ISSUE TITLE
Remove calendar button

### ISSUE THREAD

**Issue by Paramveer12** [lakshay-angrish/TODO-List#25]

**Comment by wayne9499** [comment]
why?

**Comment by lakshay-angrish** [comment]
Why are y'all spelling "Calendar" wrong??

**Comment by Paramveer12** [comment]
> why?

It looks bad

**Comment by wayne9499** [comment]
> > why?
> 
> It looks bad

okay, suggest some design or idea where to put it.. although icon would be better instead of ugly text

**Comment by Paramveer12** [comment]
Just put calendar there without the button

**Comment by lakshay-angrish** [comment]
> Just put calendar there without the button

I did suggest to do this, but @wayne9499 said it would require another library. Anyway, it would definitely look better that way.

**Comment by Paramveer12** [comment]
I have already done some work regarding that on other branch, if you wanna check out @wayne9499

**Comment by wayne9499** [comment]
yes..

**Comment by Paramveer12** [comment]
You just need to fix the bug regarding date generation, ui is done
